ansys/pyansys-tools-report

- .github/workflows/ci.yml
- .gitignore
When releasing, problems were encountered:
* No packages had been generated nor uploaded as artifacts
* Upload process failed
This fix should also be taken to branch release/0.1
> Fix packaging issues when releasing

- src/ansys/tools/report.py
- tests/test_report.py
> Fix issue with ansys_vars

- pyproject.toml
- src/ansys/tools/__init__.py
- src/ansys/tools/report.py
- tests/test_metadata.py
> Change `__version__` location to `__init__` file

- src/ansys/tools/report.py
> Change linux to posix

- .github/workflows/ci.yml
- doc/Makefile
- doc/make.bat
- doc/source/conf.py
This PR will fix #23 to generate PDF Files with release.
> Add PDF docs with release

- README.md
- doc/source/getting_started/index.rst
- pyproject.toml
> Bump to version 0.4.dev0

- README.md
- doc/styles/Vocab/ANSYS/accept.txt
- pyproject.toml
We are trying to align the CNAMEs for all pyansys tool repositories:
* <product_name>.tools.docs.pyansys.com
> Changing docs URL

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- doc/Makefile
- doc/source/conf.py
- pyproject.toml
As title says. Same approach as https://github.com/pyansys/pyansys-tools-versioning/pull/42
> Updating project to use pyansys/actions and remove requirement files

- doc/source/user_guide/index.rst
- src/ansys/tools/report/report.py
> Adding additional PyAnsys libraries to the main report

- src/ansys/tools/report/report.py
> Proper versioning import

- .github/workflows/ci.yml
- README.md
> Implementing pre-commit.ci

- .pre-commit-config.yaml
- README.md
> Implemeting blacken docs

- .github/workflows/ci.yml
- README.md
- doc/source/getting_started/index.rst
- pyproject.toml
As title says. This will require a new release
> feat: remove Python 3.7 and 3.11

- .github/workflows/ci.yml
- doc/source/_static/README.md
As title says. Trying out implementation in https://github.com/ansys/actions/pull/330
Changes needed were implemented in https://github.com/ansys/actions/pull/332
> feat: add vulnerability checks

- .github/workflows/ci.yml
- README.md
- doc/source/getting_started/index.rst
- pyproject.toml
- src/ansys/tools/report/_version.py
- src/ansys/tools/report/report.py
> feat: add 3.12 - drop 3.8

- .pre-commit-config.yaml
- src/ansys/tools/report/__init__.py
- src/ansys/tools/report/_version.py
- src/ansys/tools/report/report.py
- tests/test_metadata.py
- tests/test_report.py
> feat: add license headers

- .github/workflows/ci.yml
As title says. Giving a try to Trusted Publishers...
> feat: use trusted publisher

- src/ansys/tools/report/report.py
As the title.
I use the github dev website to submit this, soo.... pre-commit might complain.
Close #229
> fix: removing warning

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- src/ansys/tools/report/_version.py
- src/ansys/tools/report/report.py
- tests/test_metadata.py
- tests/test_report.py
> feat: switch to ruff

- .github/workflows/ci.yml
> feat: enable automerge

- .github/workflows/ci.yml
- pyproject.toml
> feat: support Python 3.13
